name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: darwin
            arch: amd64
            name: mac-intel
          - platform: darwin
            arch: arm64
            name: mac-apple-silicon
          - platform: linux
            arch: amd64
            name: linux-amd64
          - platform: linux
            arch: arm64
            name: linux-arm
          - platform: windows
            arch: amd64
            name: windows-amd64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      env:
        GOOS: ${{ matrix.platform }}
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -v -o build/${{ matrix.name }} ./...